package com.example.wearboardgames;

import android.content.Context;import android.graphics.Canvas;import android.graphics.Color;import android.graphics.Paint;import android.graphics.RectF;import android.view.HapticFeedbackConstants;
public final class MazeView extends BaseGameView{
    private static final int MODE=GameModes.MAZE;private final MazeEngine e=new MazeEngine();public MazeView(Context c){super(c);}public static boolean supportsMode(int m){return m==MODE;}@Override protected int gameMode(){return MODE;}@Override protected boolean lowerMetricIsBetter(){return true;}private RectF board(){return gamePanel(roundScreen?.12f:.09f);}@Override protected void resetGame(){e.reset();}
    @Override protected void drawGame(Canvas c){RectF b=board();drawHeader(c,"迷宫逃脱","滑动移动 · "+e.moves()+" 步");panel(c,b);float cell=Math.min(b.width(),b.height())/9f,size=cell*9,left=b.centerX()-size/2,top=b.centerY()-size/2;p.setColor(Color.rgb(112,126,145));p.setStrokeWidth(dp(1.4f));for(int i=0;i<81;i++){int x=i%9,y=i/9,w=e.walls(i);float l=left+x*cell,t=top+y*cell;if((w&1)!=0)c.drawLine(l,t,l+cell,t,p);if((w&2)!=0)c.drawLine(l+cell,t,l+cell,t+cell,p);if((w&4)!=0)c.drawLine(l,t+cell,l+cell,t+cell,p);if((w&8)!=0)c.drawLine(l,t,l,t+cell,p);}p.setColor(GOOD);c.drawCircle(left+8.5f*cell,top+8.5f*cell,cell*.24f,p);int p0=e.player();p.setColor(PRIMARY);c.drawCircle(left+(p0%9+.5f)*cell,top+(p0/9+.5f)*cell,cell*.28f,p);}
    @Override protected void onGameSwipe(float dx,float dy){int dir=Math.abs(dx)>Math.abs(dy)?(dx>0?1:3):(dy>0?2:0);if(e.move(dir)){haptic(HapticFeedbackConstants.CLOCK_TICK);if(e.won())finishRound(1,"找到出口！","用了 "+e.moves()+" 步",e.moves());invalidate();}}
    @Override protected void saveGame(){if(e.won()){clearSavedGameIfMine();return;}GameSaveManager.save(prefs,MODE,1,false,e.serialize());}@Override protected boolean restoreGame(){GameSaveManager.SaveRecord r=GameSaveManager.load(prefs,MODE);if(r==null)return false;if(e.restore(r.payload))return true;String migrated=LegacySaveMigrator.enginePayload(prefs,MODE,r.payload);if(migrated!=null&&e.restore(migrated)){GameSaveManager.save(prefs,MODE,2,r.ai,migrated);return true;}return false;}
}
