package com.example.wearboardgames;

import android.content.Context;import android.graphics.Canvas;import android.graphics.Color;import android.graphics.Paint;import android.graphics.RectF;import android.view.HapticFeedbackConstants;
public final class MinesView extends BaseGameView{
    private static final int MODE=GameModes.MINI_MINES;private final MinesEngine e=new MinesEngine();public MinesView(Context c){super(c);}public static boolean supportsMode(int m){return m==MODE;}@Override protected int gameMode(){return MODE;}private RectF board(){return gamePanel(roundScreen?.15f:.11f);}@Override protected void resetGame(){e.reset();}
    @Override protected void drawGame(Canvas c){RectF b=board();drawHeader(c,"迷你扫雷",e.over()?(e.won()?"排雷成功":"踩到地雷"):"已打开 "+e.opened()+" / 20");panel(c,b);float gap=dp(3),cell=(Math.min(b.width(),b.height())-gap*4)/5f,size=cell*5+gap*4,left=b.centerX()-size/2,top=b.centerY()-size/2;for(int y=0;y<5;y++)for(int x=0;x<5;x++){RectF r=new RectF(left+x*(cell+gap),top+y*(cell+gap),left+x*(cell+gap)+cell,top+y*(cell+gap)+cell);boolean open=e.isOpen(x,y);p.setColor(open?Color.rgb(69,76,86):SURFACE_HIGH);c.drawRoundRect(r,dp(6),dp(6),p);if(open){if(e.isMine(x,y)){p.setColor(BAD);c.drawCircle(r.centerX(),r.centerY(),cell*.20f,p);}else{int n=e.neighbors(x,y);if(n>0)text(c,String.valueOf(n),r.centerX(),r.centerY()+cell*.12f,cell*.38f,PRIMARY,true,Paint.Align.CENTER);}}}}
    @Override protected void onGameTap(float x,float y){if(e.over())return;RectF b=board();float gap=dp(3),cell=(Math.min(b.width(),b.height())-gap*4)/5f,size=cell*5+gap*4,left=b.centerX()-size/2,top=b.centerY()-size/2;int gx=(int)((x-left)/(cell+gap)),gy=(int)((y-top)/(cell+gap));if(gx<0||gx>=5||gy<0||gy>=5)return;if(e.open(gx,gy)){haptic(HapticFeedbackConstants.CLOCK_TICK);if(e.over())finishRound(e.won()?1:-1,e.won()?"排雷成功！":"踩到地雷",e.won()?"全部安全格已打开":"重新开始再试一次",e.opened());invalidate();}}
    @Override protected void saveGame(){if(e.over()){clearSavedGameIfMine();return;}GameSaveManager.save(prefs,MODE,1,false,e.serialize());}@Override protected boolean restoreGame(){GameSaveManager.SaveRecord r=GameSaveManager.load(prefs,MODE);if(r==null)return false;if(e.restore(r.payload))return true;String migrated=LegacySaveMigrator.enginePayload(prefs,MODE,r.payload);if(migrated!=null&&e.restore(migrated)){GameSaveManager.save(prefs,MODE,2,r.ai,migrated);return true;}return false;}
}
