plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.wearboardgames'
    compileSdk 35

    defaultConfig {
        applicationId 'com.example.wearboardgames'
        minSdk 30
        targetSdk 35
        versionCode 6
        versionName '6.0'
    }
}


dependencies {
    implementation "androidx.wear:wear-remote-interactions:1.2.0"
}
