package com.example.wearboardgames;

import android.content.Context;import android.graphics.Canvas;import android.graphics.Color;import android.graphics.Paint;import android.graphics.RectF;import android.view.HapticFeedbackConstants;
public final class Connect4View extends BaseGameView{
    private static final int MODE=GameModes.CONNECT4;private final Connect4Engine e=new Connect4Engine();public Connect4View(Context c){super(c);}public static boolean supportsMode(int m){return m==MODE;}@Override protected int gameMode(){return MODE;}private RectF board(){return gamePanel(roundScreen?.11f:.08f);}@Override protected void resetGame(){e.reset();}
    @Override protected void drawGame(Canvas c){RectF b=board();drawHeader(c,"四子棋",e.winner()!=0?"本局结束":(e.turn()==1?"黄方":"红方")+"走");panel(c,b);float cell=Math.min(b.width()/7f,b.height()/6f),w=cell*7,h=cell*6,left=b.centerX()-w/2,top=b.centerY()-h/2;p.setColor(Color.rgb(42,92,181));c.drawRoundRect(new RectF(left,top,left+w,top+h),dp(12),dp(12),p);for(int y=0;y<6;y++)for(int x=0;x<7;x++){int v=e.at(x,y);p.setColor(v==0?SURFACE:v==1?Color.rgb(250,209,75):Color.rgb(239,91,91));c.drawCircle(left+(x+.5f)*cell,top+(y+.5f)*cell,cell*.37f,p);}}
    @Override protected void onGameTap(float x,float y){if(e.winner()!=0)return;RectF b=board();float cell=Math.min(b.width()/7f,b.height()/6f),left=b.centerX()-cell*3.5f;int col=(int)((x-left)/cell);if(!e.drop(col))return;haptic(HapticFeedbackConstants.CLOCK_TICK);check();if(isSinglePlayer()&&e.winner()==0&&e.turn()==2){int ai=e.chooseAiMove();if(ai>=0)e.drop(ai);check();}invalidate();}
    private void check(){int w=e.winner();if(w==1)finishRound(1,"黄方四连","本局结束",1);else if(w==2)finishRound(isSinglePlayer()?-1:1,"红方四连","本局结束",1);else if(w==3)finishRound(0,"和棋","棋盘已满",1);}
    @Override protected void saveGame(){if(e.winner()!=0){clearSavedGameIfMine();return;}GameSaveManager.save(prefs,MODE,1,isSinglePlayer(),e.serialize());}@Override protected boolean restoreGame(){GameSaveManager.SaveRecord r=GameSaveManager.load(prefs,MODE);if(r==null)return false;if(e.restore(r.payload))return true;String migrated=LegacySaveMigrator.enginePayload(prefs,MODE,r.payload);if(migrated!=null&&e.restore(migrated)){GameSaveManager.save(prefs,MODE,2,r.ai,migrated);return true;}return false;}
}
