package com.example.wearboardgames;

import android.content.Context;import android.graphics.Canvas;import android.graphics.Color;import android.graphics.Paint;import android.graphics.RectF;import android.view.HapticFeedbackConstants;

/** 15x15 Gomoku View + pure engine. */
public final class GomokuView extends BaseGameView{
    private static final int MODE=GameModes.GOMOKU;private final GomokuEngine e=new GomokuEngine();
    public GomokuView(Context c){super(c);}public static boolean supportsMode(int m){return m==MODE;}@Override protected int gameMode(){return MODE;}private RectF board(){return gamePanel(roundScreen?.08f:.06f);}@Override protected void resetGame(){e.reset();}
    @Override protected void drawGame(Canvas c){RectF b=board();drawHeader(c,"五子棋",e.winner()!=0?"本局结束":(e.turn()==1?"黑方":"白方")+"走");panel(c,b);float cell=Math.min(b.width(),b.height())/15f,size=cell*14,left=b.centerX()-size/2,top=b.centerY()-size/2;p.setColor(Color.rgb(171,132,81));p.setStrokeWidth(dp(1));for(int i=0;i<15;i++){c.drawLine(left,top+i*cell,left+size,top+i*cell,p);c.drawLine(left+i*cell,top,left+i*cell,top+size,p);}for(int y=0;y<15;y++)for(int x=0;x<15;x++){int v=e.at(x,y);if(v==0)continue;p.setColor(v==1?Color.rgb(28,30,34):Color.rgb(238,238,235));c.drawCircle(left+x*cell,top+y*cell,cell*.39f,p);if(x==e.lastX()&&y==e.lastY()){p.setColor(v==1?Color.WHITE:Color.BLACK);c.drawCircle(left+x*cell,top+y*cell,cell*.08f,p);}}}
    @Override protected void onGameTap(float x,float y){if(e.winner()!=0)return;RectF b=board();float cell=Math.min(b.width(),b.height())/15f,size=cell*14,left=b.centerX()-size/2,top=b.centerY()-size/2;int gx=Math.round((x-left)/cell),gy=Math.round((y-top)/cell);if(!e.place(gx,gy))return;haptic(HapticFeedbackConstants.CLOCK_TICK);check();if(isSinglePlayer()&&e.winner()==0&&e.turn()==2){int[]m=e.chooseAiMove();if(m!=null)e.place(m[0],m[1]);check();}invalidate();}
    private void check(){if(e.winner()==1)finishRound(1,"黑方五连","本局结束",1);else if(e.winner()==2)finishRound(isSinglePlayer()?-1:1,"白方五连","本局结束",1);else if(e.winner()==3)finishRound(0,"和棋","棋盘已满",1);}
    @Override protected void saveGame(){if(e.winner()!=0){clearSavedGameIfMine();return;}GameSaveManager.save(prefs,MODE,1,isSinglePlayer(),e.serialize());}@Override protected boolean restoreGame(){GameSaveManager.SaveRecord r=GameSaveManager.load(prefs,MODE);if(r==null)return false;if(e.restore(r.payload))return true;String migrated=LegacySaveMigrator.enginePayload(prefs,MODE,r.payload);if(migrated!=null&&e.restore(migrated)){GameSaveManager.save(prefs,MODE,2,r.ai,migrated);return true;}return false;}
}
