package com.example.wearboardgames;

import android.content.Context;import android.graphics.Canvas;import android.graphics.Color;import android.graphics.Paint;import android.graphics.RectF;import android.view.HapticFeedbackConstants;
public final class ReversiView extends BaseGameView{
    private static final int MODE=GameModes.REVERSI;private final ReversiEngine e=new ReversiEngine();public ReversiView(Context c){super(c);}public static boolean supportsMode(int m){return m==MODE;}@Override protected int gameMode(){return MODE;}private RectF board(){return gamePanel(roundScreen?.12f:.09f);}@Override protected void resetGame(){e.reset();}
    @Override protected void drawGame(Canvas c){RectF b=board();drawHeader(c,"黑白棋","黑 "+e.count(1)+" · 白 "+e.count(2)+(e.winner()==0?" · "+(e.turn()==1?"黑":"白")+"走":""));panel(c,b);float cell=Math.min(b.width(),b.height())/6f,size=cell*6,left=b.centerX()-size/2,top=b.centerY()-size/2;p.setColor(Color.rgb(42,124,82));c.drawRoundRect(new RectF(left,top,left+size,top+size),dp(10),dp(10),p);p.setColor(Color.rgb(34,79,58));p.setStrokeWidth(dp(1));for(int i=1;i<6;i++){c.drawLine(left+i*cell,top,left+i*cell,top+size,p);c.drawLine(left,top+i*cell,left+size,top+i*cell,p);}for(int y=0;y<6;y++)for(int x=0;x<6;x++){int v=e.at(x,y);if(v>0){p.setColor(v==1?Color.rgb(28,30,34):Color.rgb(241,241,237));c.drawCircle(left+(x+.5f)*cell,top+(y+.5f)*cell,cell*.36f,p);}else if(e.legal(x,y)){p.setColor(Color.argb(80,180,230,190));c.drawCircle(left+(x+.5f)*cell,top+(y+.5f)*cell,cell*.10f,p);}}}
    @Override protected void onGameTap(float x,float y){if(e.winner()!=0)return;RectF b=board();float cell=Math.min(b.width(),b.height())/6f,left=b.centerX()-cell*3,top=b.centerY()-cell*3;int gx=(int)((x-left)/cell),gy=(int)((y-top)/cell);if(gx<0||gx>=6||gy<0||gy>=6||!e.move(gx,gy))return;haptic(HapticFeedbackConstants.CLOCK_TICK);if(isSinglePlayer()&&e.winner()==0&&e.turn()==2){int[]m=e.chooseAiMove();if(m!=null)e.move(m[0],m[1]);}check();invalidate();}
    private void check(){int w=e.winner();if(w!=0)finishRound(w==1?1:w==2&&isSinglePlayer()?-1:1,w==3?"和棋":w==1?"黑方获胜":"白方获胜","黑 "+e.count(1)+" · 白 "+e.count(2),Math.max(e.count(1),e.count(2)));}
    @Override protected void saveGame(){if(e.winner()!=0){clearSavedGameIfMine();return;}GameSaveManager.save(prefs,MODE,1,isSinglePlayer(),e.serialize());}@Override protected boolean restoreGame(){GameSaveManager.SaveRecord r=GameSaveManager.load(prefs,MODE);if(r==null)return false;if(e.restore(r.payload))return true;String migrated=LegacySaveMigrator.enginePayload(prefs,MODE,r.payload);if(migrated!=null&&e.restore(migrated)){GameSaveManager.save(prefs,MODE,2,r.ai,migrated);return true;}return false;}
}
