package com.example.wearboardgames;

import android.content.Context;import android.graphics.Canvas;import android.graphics.Color;import android.graphics.Paint;import android.graphics.RectF;import android.view.HapticFeedbackConstants;
public final class SokobanView extends BaseGameView{
    private static final int MODE=GameModes.SOKOBAN;private final SokobanEngine e=new SokobanEngine();public SokobanView(Context c){super(c);}public static boolean supportsMode(int m){return m==MODE;}@Override protected int gameMode(){return MODE;}@Override protected boolean lowerMetricIsBetter(){return true;}private RectF board(){return gamePanel(roundScreen?.13f:.10f);}@Override protected void resetGame(){e.load(0);}
    @Override protected void drawGame(Canvas c){RectF b=board();drawHeader(c,"推箱子","第 "+(e.level()+1)+" 关 · "+e.moves()+" 步");panel(c,b);float cell=Math.min(b.width()/SokobanEngine.W,b.height()/SokobanEngine.H),w=cell*SokobanEngine.W,h=cell*SokobanEngine.H,left=b.centerX()-w/2,top=b.centerY()-h/2;for(int i=0;i<SokobanEngine.W*SokobanEngine.H;i++){int x=i%SokobanEngine.W,y=i/SokobanEngine.W;RectF r=new RectF(left+x*cell,top+y*cell,left+(x+1)*cell,top+(y+1)*cell);if(e.wall(i)){p.setColor(Color.rgb(77,84,96));c.drawRoundRect(r,dp(3),dp(3),p);}else if(e.goal(i)){p.setColor(GOOD);c.drawCircle(r.centerX(),r.centerY(),cell*.13f,p);}if(e.box(i)){p.setColor(e.goal(i)?GOOD:Color.rgb(218,153,73));c.drawRoundRect(new RectF(r.left+cell*.14f,r.top+cell*.14f,r.right-cell*.14f,r.bottom-cell*.14f),dp(4),dp(4),p);}}int pl=e.player(),px=pl%SokobanEngine.W,py=pl/SokobanEngine.W;p.setColor(PRIMARY);c.drawCircle(left+(px+.5f)*cell,top+(py+.5f)*cell,cell*.28f,p);}
    @Override protected void onGameSwipe(float dx,float dy){int dir=Math.abs(dx)>Math.abs(dy)?(dx>0?1:3):(dy>0?2:0);if(e.move(dir)){haptic(HapticFeedbackConstants.CLOCK_TICK);if(e.won()){int moves=e.moves();if(e.level()<SokobanEngine.levelCount()-1){e.nextLevel();sound(SoundManager.CLEAR);}else finishRound(1,"全部通关！","最后一关 "+moves+" 步",moves);}invalidate();}}
    @Override protected void saveGame(){GameSaveManager.save(prefs,MODE,1,false,e.serialize());}@Override protected boolean restoreGame(){GameSaveManager.SaveRecord r=GameSaveManager.load(prefs,MODE);if(r==null)return false;if(e.restore(r.payload))return true;String migrated=LegacySaveMigrator.enginePayload(prefs,MODE,r.payload);if(migrated!=null&&e.restore(migrated)){GameSaveManager.save(prefs,MODE,2,r.ai,migrated);return true;}return false;}
}
