package com.example.wearboardgames;

import android.content.Context;import android.graphics.Canvas;import android.graphics.Color;import android.graphics.Paint;import android.graphics.RectF;import android.view.HapticFeedbackConstants;
public final class SudokuView extends BaseGameView{
    private static final int MODE=GameModes.SUDOKU;private final SudokuEngine e=new SudokuEngine();private int selected=-1;public SudokuView(Context c){super(c);}public static boolean supportsMode(int m){return m==MODE;}@Override protected int gameMode(){return MODE;}private RectF board(){return gamePanel(roundScreen?.17f:.13f);}@Override protected void resetGame(){e.reset((int)(System.nanoTime()%3));selected=-1;}
    @Override protected void drawGame(Canvas c){RectF b=board();drawHeader(c,"数独","轻点格子循环 1–4 · 冲突会标红");panel(c,b);float cell=Math.min(b.width(),b.height())/4f,size=cell*4,left=b.centerX()-size/2,top=b.centerY()-size/2;for(int y=0;y<4;y++)for(int x=0;x<4;x++){RectF r=new RectF(left+x*cell,top+y*cell,left+(x+1)*cell,top+(y+1)*cell);p.setColor(selected==y*4+x?Color.rgb(57,70,88):SURFACE_HIGH);c.drawRect(r,p);int v=e.at(x,y);if(v>0)text(c,String.valueOf(v),r.centerX(),r.centerY()+cell*.15f,cell*.46f,e.conflict(x,y)?BAD:e.fixed(x,y)?TEXT:PRIMARY,e.fixed(x,y),Paint.Align.CENTER);}p.setStyle(Paint.Style.STROKE);p.setColor(Color.rgb(99,109,125));for(int i=0;i<=4;i++){p.setStrokeWidth(i%2==0?dp(2):dp(1));c.drawLine(left+i*cell,top,left+i*cell,top+size,p);c.drawLine(left,top+i*cell,left+size,top+i*cell,p);}p.setStyle(Paint.Style.FILL);}
    @Override protected void onGameTap(float x,float y){RectF b=board();float cell=Math.min(b.width(),b.height())/4f,left=b.centerX()-cell*2,top=b.centerY()-cell*2;int gx=(int)((x-left)/cell),gy=(int)((y-top)/cell);if(gx<0||gx>=4||gy<0||gy>=4)return;selected=gy*4+gx;if(!e.fixed(gx,gy)){e.cycle(gx,gy);haptic(HapticFeedbackConstants.CLOCK_TICK);if(e.solved())finishRound(1,"数独完成！","所有行列与宫都正确",1);}invalidate();}
    @Override protected void saveGame(){if(e.solved()){clearSavedGameIfMine();return;}GameSaveManager.save(prefs,MODE,1,false,e.serialize());}@Override protected boolean restoreGame(){GameSaveManager.SaveRecord r=GameSaveManager.load(prefs,MODE);if(r==null)return false;if(e.restore(r.payload))return true;String migrated=LegacySaveMigrator.enginePayload(prefs,MODE,r.payload);if(migrated!=null&&e.restore(migrated)){GameSaveManager.save(prefs,MODE,2,r.ai,migrated);return true;}return false;}
}
